Feature/instance screen
cos301-2019-se/Amazon-Dash pull request #60
Opened 2019-07-17 10:19 UTC by 1tsS0meth1ng

2019-07-17 10:42 UTC, Musaki5414 approved these changes
Cools staff

2019-07-17 18:01 UTC, nat212 requested changes

2019-07-17 18:01 UTC, nat212 commented on .gitignore
> +
Why the newline?

2019-07-17 18:01 UTC, nat212 commented on backend/__main__.py
> +    config = Config('../setup.cfg')
You're supposed to run the backend using `python3 -m backend` from the root folder, so this should stay as it was

2019-07-17 18:01 UTC, nat212 commented on backend/__main__.py
> +    config = Config('../setup.cfg')
This will break a lot of things like heroku, etc

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/Chart.vue
> +  @Prop() public options
```suggestion
  @Prop() public options!
```

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/Chart.vue
> +  @Prop() public options
Tsc will complain otherwise. Also please add a type annotation or it will complain about that too

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/Chart.vue
> +  @Prop() public options
Wait hang on, is this file even used? If not, please delete it

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +                color="cyan"
Maybe add different colours for different metrics? Idk just an idea

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +            <span class="headline">{{ metric.id }}</span>
Use `metric.name` (I think it's called name, just double check)

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +import {Metric, MetricData, metricOptions} from '@/models/metric'
Spacing ^^

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +import {MetricViewClass} from '@/models/metricView'
Same here

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +    @Prop() public metric: MetricViewClass
```suggestion
    @Prop() public metric!: MetricViewClass
```

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +    public bounds: any = []
Don't use any, use a proper type

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/MetricCard.vue
> +        return metricOptions.find((i: any) => {
Again, use a proper type

2019-07-17 18:01 UTC, nat212 commented on frontend/src/components/ServiceCard.vue
> +      <v-btn icon small flat style="float: right" v-on:click="goToMetricView(instance.id)"><v-icon>info</v-icon></v-btn>
Rather use `@click` as it's shorter

2019-07-17 18:01 UTC, nat212 commented on frontend/src/models/MetricViewDataPoint.ts
> +export class MetricViewDataPointClass {
Rather make this `MetricViewDataPoint` and the interface `MetricViewDataPointData`

2019-07-17 18:01 UTC, nat212 commented on frontend/src/models/metricView.ts
> +import {MetricViewDataPoint, MetricViewDataPointClass} from '@/models/MetricViewDataPoint'
Spacing ^^

2019-07-17 18:01 UTC, nat212 commented on frontend/src/models/metricView.ts
> +      })
This can be condensed to
```js
this.data = data.data.map(value => new MetricViewDataPointClass(value))
```

2019-07-17 18:01 UTC, nat212 commented on frontend/src/router.ts
> +      {
Indentation is a bit off

2019-07-17 18:01 UTC, nat212 commented on frontend/src/router.ts
> +          component: Metrics,
Maybe rather use lazy loading, so
```js
component: () => import(/* webpackChunkName: 'metrics' */ './views/Metrics.vue'),
```
Then you can remove the top level import as well

2019-07-17 18:01 UTC, nat212 commented on frontend/src/store/mutations.ts
> +import {MetricView, MetricViewClass} from '@/models/metricView'
More spacing yay!

2019-07-17 18:01 UTC, nat212 commented on frontend/src/store/types.ts
> +    metrics: any[]
Please don't use any

2019-07-17 18:01 UTC, nat212 commented on frontend/src/views/Metrics.vue
> +    @Prop() public instanceId: string
```suggestion
    @Prop() public instanceId!: string
```

2019-07-17 18:01 UTC, nat212 commented on frontend/src/views/Metrics.vue
> +    public searchFilter: string = ''
Remove the type annotation, it's unnecessary

2019-07-17 18:01 UTC, nat212 commented on frontend/src/views/Metrics.vue
> +</style>
This is empty, remove it

2019-07-18 07:57 UTC, 1tsS0meth1ng commented on frontend/src/components/Chart.vue
> +  @Prop() public options
I cant seem to even find it on my end

2019-07-18 07:58 UTC, 1tsS0meth1ng commented on frontend/src/components/MetricCard.vue
> +                color="cyan"
I believe it'd seem too all over the place I'd prefer to keep it one colour.

2019-07-18 07:59 UTC, 1tsS0meth1ng commented on frontend/src/components/MetricCard.vue
> +            <span class="headline">{{ metric.id }}</span>
The metric is stored as id

2019-07-18 18:23 UTC, nat212 approved these changes

2019-07-18 18:25 UTC, silvaportal approved these changes

2019-07-18 18:43 UTC, merged